/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eyesmart_testapplication_android_TestJni */

#ifndef _Included_com_eyesmart_testapplication_android_TestJni
#define _Included_com_eyesmart_testapplication_android_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eyesmart_testapplication_android_TestJni
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_eyesmart_testapplication_android_TestJni_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
